name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: ./

      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: ./dist/linux